### ISSUE TITLE
Could you please tell me what is NEW-TEST-ID

### ISSUE THREAD

**Issue by srikpunu** [hyperlab/TiMixpanel#27]
Could you please tell me what is NEW-TEST-ID

```
// mixpanel.createAliasForId('NEW-TEST-ID', mixpanel.distinctId);
mixpanel.createAlias('NEW-TEST-ID');
```

**Comment by jonatansberg** [comment]
The `'NEW-TEST-ID'` is whatever ID you want to assign your user. You can read more about aliasing here:
https://mixpanel.com/docs/integration-libraries/using-mixpanel-alias

**Comment by srikpunu** [comment]
Thank you, What if I don't want to track by user ( Since I don't have login/singup option in my app ) and just want to track only screens or buttons clicks. Just want to find how many people click here and there..

**Comment by tbjers** [comment]
You can track by device ID or similar in that case.

**Comment by jonatansberg** [comment]
If you only want to track user actions you don't need to call createAlias at all. Mixpanel will generate a unique id for the current installation of the app and use that id by default.
