### ISSUE TITLE
For android app, not able to update super properties

### ISSUE THREAD

**Issue by Niral2110** [hyperlab/TiMixpanel#30]
Hi, 

I am using version 0.9 for android with titanium SDK 5.1.2 GA.
Basically I need to increment a super property whenever a page is traversed by user.
For that I am using following code. here "count" variable holds total counts, fetched from database.

`mixpanel.registerSuperProperties({
'myPageViewCount' : count++
});`

But what i noticed is, when event is traversed first time, it registers property with initial value, & afterwards it remains same, even if I am setting it with increment.

Help required urgently, I am in between of something very important.
Thanks in advance.

**Comment by jonatansberg** [comment]
Hello @Niral2110,
I'm afraid that I'm not in a very good position to help you at the moment. However, this module is only a thin wrapper around the Mixpanel SDK. Try updating their SDK and rebuild the module to see if that fixes your problem.

If you fix it, a pull request would be very appreciated! :)

Cheers,
Jonatan

**Comment by Niral2110** [comment]
Hi @mrlundis,

I went inside " TiMixpanel/android/src/se/hyperlab/mixpanel/TimixpanelModule.java" file & found a small mistake in it. see below code.


it should be reverse of what is written over there in .java file.

**Comment by Niral2110** [comment]
![capture](https://cloud.githubusercontent.com/assets/17088464/14045690/26d33972-f294-11e5-8fbc-5c099b148eb9.PNG)

There is a bug in core java file as above, it should be reverese of what it is right now.
